### ISSUE TITLE
Empty dependency list in lockfile

### ISSUE THREAD

**Issue by g2p** [AltGr/opam-lock#1]
Thank you for a tool that has the potential to make reproducible builds much easier.
For some reason, the lockfile I get is almost empty right now, and doesn't contain a "depends" key.
Is there any way to debug this?
Here are the file contents:
```
opam-version: "2.0"
maintainer: "g2p.code@gmail.com"
authors: [ "Gabriel de Perthuis"]
homepage: "https://github.com/g2p/wodan"
dev-repo: "git+https://github.com/g2p/wodan.git"
bug-reports: "https://github.com/g2p/wodan/issues"
name: "wodan"
version: "dev"


build: [
  [ "dune" "subst"] {pinned}
  [ "dune" "build" "-p" name "-j" jobs ]
]

tags: "org:mirage"
```

Which is a stripped version of the original, see https://github.com/g2p/wodan/blob/master/wodan.opam

**Comment by g2p** [comment]
Turns out this was caused by an error in the original Opam file; I had one package name containing a dot which it shouldn't have. Not sure you want to keep the issue open, I guess extra error checking would be welcome.

**Comment by AltGr** [comment]
Closing this repository, feature integrated into opam.
