### ISSUE TITLE
Don't lock the OCaml compiler

### ISSUE THREAD

**Issue by g2p** [AltGr/opam-lock#2]
The OCaml compiler should probably be excluded from the locked set.
It might also be useful to take a list of packages not to lock.

**Comment by ELLIOTTCABLE** [comment]
Personally, I find this necessary. The package-versions I have installed are specific to the OCaml point-release; changing the OCaml version would invalidate constraints on many of the packages defined in the lockfile. That is, a given lockfile is only meaningful for a *particular point-release and variant of the OCaml compiler*, in the same way that the lockfile is only meaningful when taken as a whole w.r.t. any *other* package currently included in it.

**Comment by AltGr** [comment]
Closing this repository, feature integrated into opam.
